name: BuildNow Terraform Init (DEPRECATED)
description: Initiate Terraform with Sync as HTTP backend.

inputs:
  PLUGIN_NAME:
    required: true
    description: Name of the BuildNow Plugin
  TERRAFORM_DIRECTORY:
    required: true
    description: The path to the Terraform root directory
  TWILIO_API_KEY:
    required: true
    description: The Twilio API key
  TWILIO_API_SECRET:
    required: true
    description: The Twilio API secret
  SYNC_SERVICE_SID:
    required: false
    description: |
      (Optional) Override the Sync Service Sid for where the Terraform state file is stored.

      Defaults to the Default Sync Service `default`
    default: default
  SYNC_MAP_NAME:
    required: false
    description: |
      (Optional) Override the Sync Map UniqueName for where the Terraform state file is stored.

      Defaults to `build-now-state-manager-files`
    default: build-now-state-manager-files
  BACKEND_PROXY_PORT:
    required: false
    description: |
      (Optional) Override the port used to host the local proxy server for Terraform backend operations.
      Set this if the default port conflicts with other steps in the current runner/job.

      Defaults to 9464
    default: "9464"
  # Obsolete Inputs
  TERRAFORM_BASIC_USERNAME:
    required: false
    description: (OBSOLETE) No longer has an effect
  TERRAFORM_BASIC_PASSWORD:
    required: false
    description: (OBSOLETE) No longer has an effect

runs:
  using: composite
  steps:
    - name: Validate Inputs
      shell: bash
      run: |
        fail=""
        [[ -z "${{ inputs.PLUGIN_NAME }}" ]] && echo "::error::Missing PLUGIN_NAME in inputs" && fail=1
        [[ -z "${{ inputs.TERRAFORM_DIRECTORY }}" ]] && echo "::error::Missing TERRAFORM_DIRECTORY in inputs" && fail=1
        [[ -z "${{ inputs.TWILIO_API_KEY }}" ]] && echo "::error::Missing TWILIO_API_KEY in inputs" && fail=1
        [[ -z "${{ inputs.TWILIO_API_SECRET }}" ]] && echo "::error::Missing TWILIO_API_SECRET in inputs" && fail=1

        [[ -n "$fail" ]] && exit 1 || exit 0

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - name: Start Backend Proxy
      uses: zingdevlimited/actions-helpers/build-now/terraform-init/backend-proxy@v3
      with:
        PLUGIN_NAME: ${{ inputs.PLUGIN_NAME }}
        BACKEND_PROXY_PORT: ${{ inputs.BACKEND_PROXY_PORT }}
        TWILIO_API_KEY: ${{ inputs.TWILIO_API_KEY }}
        TWILIO_API_SECRET: ${{ inputs.TWILIO_API_SECRET }}
        SYNC_SERVICE_SID: ${{ inputs.SYNC_SERVICE_SID }}
        SYNC_MAP_NAME: ${{ inputs.SYNC_MAP_NAME }}
        ACTION_PATH: ${{ github.action_path }}

    - name: Terraform Init
      shell: bash
      working-directory: ${{ inputs.TERRAFORM_DIRECTORY }}
      run: terraform init -backend-config="address=http://localhost:${{ env.CURRENT_BACKEND_PROXY_PORT }}"
  
    - name: Terraform Validate
      shell: bash
      working-directory: ${{ inputs.TERRAFORM_DIRECTORY }}
      run: terraform validate
