name: "Update Twilio Flex Worker Skills"
description: Update the Twilio Flex Worker Skills Configuration.
inputs:
  SIMPLE_SKILLS:
    required: false
    description: A newline separated list of Flex skills that do not have any levels
  COMPLEX_SKILLS:
    required: false
    description: |
      A JSON array of skill objects where you can define levels. The objects must be of the structure:

      ```json
      {
        "name": "skillName",
        "multivalue": false | true,
        "minimum": null | number,
        "maximum": null | number,
      }
      ```
  MODE:
    required: false
    description: Set to `merge` or `replace`. Defaults to `merge`
    default: merge
  TWILIO_API_KEY:
    required: true
    description: Twilio API Key
  TWILIO_API_SECRET:
    required: true
    description: Twilio API Secret

runs:
  using: node20
  main: index.mjs
