name: "Deploy Flex Plugin Asset"
description: Deploy a Flex Plugin bundle asset to the Default Plugin Service
inputs:
  FILE_PATH:
    required: true
    description: The file path to the plugin javascript bundle file
  PLUGIN_NAME:
    required: true
    description: The plugin name (as defined in package.json)
  PLUGIN_VERSION:
    required: true
    description: The plugin version (as defined in package.json)
  TWILIO_API_KEY:
    required: true
    description: The Twilio API Key
  TWILIO_API_SECRET:
    required: true
    description: The Twilio API Secret
  ALLOW_VERSION_OVERWRITE:
    required: false
    description: (Optional) Set this flag as 'true' to overwrite the deployed bundle if it already exists
outputs:
  ASSET_URL:
    description: The full URL to the deployed bundle asset of the Flex Plugin
  DEPLOY_SID:
    description: The SID of the Severless Asset Deployment
  
runs:
  using: node20
  main: index.mjs