name: Update Taskrouter
description: Update Taskrouter Configuration of a Workspace.

inputs:
  CONFIG_PATH:
    required: true
    description: Path to the taskrouter config json file. **Ensure this file is checked out**.
  TWILIO_API_KEY:
    required: true
    description: The Twilio Api Key
  TWILIO_API_SECRET:
    required: true
    description: The Twilio Api Secret
  WORKSPACE_NAME:
    required: false
    description: |
      **For non-Flex Accounts**. The Friendly Name of an existing Taskrouter Workspace.
      Omit this parameter if you are using the default Flex Workspace.

outputs:
  RESOURCES:
    description: "JSON of the resources created by this action"
  WORKSPACE_SID:
    description: "The Workspace Sid of the Taskrouter resources"

runs:
  using: node20
  main: index.mjs
