import { listDeleteUpdateCreate } from "./shared.mjs";

const DEFAULTS = {
  Services: [
    {
      FriendlyName: "Flex Plugins Service (Autogenerated) - Do Not Delete",
      UniqueName: "default",
    },
  ],
};

export const resetServerless = async () => {
  await listDeleteUpdateCreate(
    "https://serverless.twilio.com/v1",
    "Services",
    DEFAULTS.Services,
    { skipCreate: true, skipUpdate: true }
  );
};
