name: "Create Flex Plugin Version"
description: Create a Flex Plugin Version from a URL
inputs:
  PLUGIN_NAME:
    required: true
    description: Plugin name
  PLUGIN_VERSION:
    required: true
    description: Plugin version
  ASSET_URL:
    required: true
    description: The full URL to the deployed bundle asset of the Flex Plugin
  TWILIO_API_KEY:
    required: true
    description: Twilio API Key
  TWILIO_API_SECRET:
    required: true
    description: Twilio API Secret
outputs:
  PLUGIN_VERSION_SID:
    description: The Sid of the created/existing Plugin Version.
  
runs:
  using: node20
  main: index.mjs