name: "Update Twilio Functions Variables"
description: Update the Environment Variables saved to a Twilio Functions Service
inputs:
  SERVICE_NAME:
    required: true
    description: The unique name of the Twilio Functions Service
  ENVIRONMENT_SUFFIX:
    required: false
    description: (Optional) The domain suffix of the Twilio Functions Environment
  VARIABLES_ENV:
    required: true
    description: The Environment Variable key/value pairs to deploy (in .env format)
  OPTIONAL_VARIABLES:
    required: false
    description: (Optional) List of Environment Variable keys that are optional. Will not error if empty, and will not delete existing value.
  TWILIO_API_KEY:
    required: true
    description: Twilio API Key
  TWILIO_API_SECRET:
    required: true
    description: Twilio API Secret

runs:
  using: node20
  main: index.mjs