name: "Get Twilio Functions Service"
description: Get the SIDs and BASE_URL of a deployed Functions Service
inputs:
  SERVICE_NAME:
    required: true
    description: The unique name of the Twilio Functions Service
  ENVIRONMENT_SUFFIX:
    required: false
    description: (Optional) The domain suffix of the Twilio Functions Environment
  IGNORE_NOT_FOUND:
    required: false
    description: (Optional) Set to 'true' to not error if the service is not found, and instead return empty outputs.
  TWILIO_API_KEY:
    required: true
    description: Twilio API Key
  TWILIO_API_SECRET:
    required: true
    description: Twilio API Secret
outputs:
  BASE_URL:
    description: "The Functions Service Base URL. e.g.: https://domain-name-1234-stage.twil.io"
  SERVICE_SID:
    description: "The SID of the Functions Service"
  ENVIRONMENT_SID:
    description: "The SID of the Functions Environment"
  BUILD_SID:
    description: "The SID of the latest Build deployed to the Functions Environment (if it exists)"

runs:
  using: node20
  main: index.mjs
