name: "Release Flex Plugin Versions"
description: "Release a list of Flex Plugin Versions"
inputs:
  PLUGIN_VERSIONS:
    description: env formatted list of key-value pairs where the key is a plugin unique name, and the value is the plugin version
    required: true
  RELEASE_NAME:
    description: The name of the release to create
    required: true
  RELEASE_DESCRIPTION:
    description: (Optional) The description of the release to create
    required: false
  TWILIO_API_KEY:
    required: true
    description: The SID of a Twilio API Key
  TWILIO_API_SECRET:
    required: true
    description: The secret value of TWILIO_API_KEY

runs:
  using: node20
  main: index.mjs