name: "Get Twilio Resource SID"
description: Fetch the SID of an existing Twilio resource from a Twilio account.
inputs:
  TWILIO_AREA:
    required: true
    description: "The API subdomain. e.g.: `sync`, `studio`, `taskrouter`"
  API_TYPE:
    required: true
    description: "The type of resource in the format used in the API call URL path. e.g.: `Services`, `Flows`, `TaskQueues`"
  SEARCH_BY:
    required: true
    description: "The name of the field on a resource object that you want to match in search. e.g.: `friendly_name`, `unique_name`"
  SEARCH_VALUE:
    required: true
    description: "Used to select your resource by ensuring `resource.<SEARCH_BY> == <SEARCH_VALUE>`"
  VERSION:
    required: false
    default: v1
    description: "The API version. If omitted it defaults to `v1`. For some twilio areas (e.g. studio) it should be set to `v2`."
  TWILIO_API_KEY:
    required: true
    description: Twilio API Key
  TWILIO_API_SECRET:
    required: true
    description: Twilio API Secret
  ALLOW_NO_RESULTS:
    required: false
    description: |
      (Optional) set to `true` to not throw an error if the resource could not be found.

      Instead, the `SID` output will return an empty string.
outputs:
  SID:
    description: The resulting SID
  
runs:
  using: node20
  main: index.mjs