name: "Test Twilio Flex Plugin"

on:
  workflow_call:
    inputs:
      PLUGIN_DIRECTORY:
        type: string
        required: true
        description: The path to the Flex Plugin base directory (where package.json is located)
      TEST_COMMAND:
        type: string
        required: true
        description: The test command
      TEST_COMMAND_DIRECTORY:
        type: string
        required: false
        description: (Optional) defaults to install directory
      INSTALL_DIRECTORY:
        type: string
        required: false
        default: .
        description: (Optional) The path to the directory to call yarn install in. Defaults to root
      INSTALL_FLAGS:
        type: string
        required: false
        description: (Optional) Override yarn install flags
        default: "--immutable"
      COVERAGE_LCOV_FILE:
        type: string
        required: false
        description: (Optional) Add path to lcov-file to output test coverage on PR
      NODE_VERSION:
        type: string
        required: false
        description: (Optional) Override Node Version (Default to engines.node or 18 if not found)

jobs:
  plugin_test:
    runs-on: ubuntu-22.04
    env:
      PLUGIN_DIR: ${{ inputs.PLUGIN_DIRECTORY != '' && inputs.PLUGIN_DIRECTORY || '.' }}
      INSTALL_DIR: ${{ inputs.INSTALL_DIRECTORY != '' && inputs.INSTALL_DIRECTORY || '.' }}
      NODE_VERSION: ${{ inputs.NODE_VERSION }}

    steps:
      - name: Checkout ${{ github.repository }}@${{ github.ref_name }}
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout zingdevlimited/actions-helpers@v4
        uses: actions/checkout@v4
        with:
          repository: zingdevlimited/actions-helpers
          path: helpers
          ref: v4

      - name: Resolve Dependencies
        run: |
          if [ "${{ env.INSTALL_DIR }}" == "." ]; then
            echo "CACHE_DEPENDENCY_PATH=main/yarn.lock" >> "$GITHUB_ENV"
          else
            echo "CACHE_DEPENDENCY_PATH=main/${{ env.INSTALL_DIR }}/yarn.lock" >> "$GITHUB_ENV"
          fi

          if [ -z "${{ env.NODE_VERSION }}" ]; then
            nodeVer=$(cat main/${{ env.PLUGIN_DIR }}/package.json | jq -r '.engines.node // empty')
            if [ -z "$nodeVer" ]; then
              nodeVer=$(cat main/${{ env.INSTALL_DIR }}/package.json | jq -r '.engines.node // empty')
            fi
            if [ -z "$nodeVer" ]; then
              nodeVer="18.x"
            fi
          fi
          echo "NODE_VERSION=$nodeVer" >> "$GITHUB_ENV"

      - name: Set up Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
          cache-dependency-path: ${{ env.CACHE_DEPENDENCY_PATH }}

      - name: Setup Flex CLI
        uses: ./helpers/setup-flex-cli
        id: flexCli
        with:
          PLUGIN_DIRECTORY: main/${{ inputs.PLUGIN_DIRECTORY }}

      - name: Install Dependencies
        working-directory: main/${{ inputs.INSTALL_DIRECTORY }}
        run: yarn install ${{ inputs.INSTALL_FLAGS }}

      - name: Test ${{ steps.flexCli.outputs.PLUGIN_NAME }}
        working-directory: main/${{ inputs.TEST_COMMAND_DIRECTORY != '' && inputs.TEST_COMMAND_DIRECTORY || inputs.INSTALL_DIRECTORY }}
        run: ${{ inputs.TEST_COMMAND }}
        env:
          TWILIO_ACCOUNT_SID: ACX # Dummy credentials for CLI. Not needed to test
          TWILIO_AUTH_TOKEN: X

      - name: Output plugin coverage
        if: github.event_name == 'pull_request' && inputs.COVERAGE_LCOV_FILE != ''
        uses: romeovs/lcov-reporter-action@dda1c9b1fa1622b225e9acd87a248751dbcc6ada # v0.3.1
        with:
          title: Plugin Coverage
          lcov-file: ${{ inputs.COVERAGE_LCOV_FILE }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          delete-old-comments: true
